#!/usr/bin/env python3
"""Record a SHA-256 for every shipped source file, for the runtime integrity check.

Run by the build and verified by CI, so a manifest can never drift from the code it describes —
a stale one would either fail every install or, worse, pass while describing something else.

`_manifest.py` itself is excluded: it cannot contain its own digest.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "src" / "ranbval_sdk"
MANIFEST = PKG / "_internal" / "_manifest.py"

sys.path.insert(0, str(ROOT / "src"))
from ranbval_sdk._internal.integrity import file_digest  # noqa: E402


def build() -> dict[str, str]:
    digests = {}
    for path in sorted(PKG.rglob("*.py")):
        if path == MANIFEST:
            continue
        digests[str(path.relative_to(PKG))] = file_digest(path)
    return digests


def render(digests: dict[str, str]) -> str:
    lines = [
        '"""Generated by scripts/gen_manifest.py — do not edit.',
        "",
        "SHA-256 of every shipped source file, compared at the first decrypt by",
        "``ranbval_sdk._internal.integrity``. Regenerated by the build; CI fails if it is stale.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "FILE_DIGESTS: dict[str, str] = {",
    ]
    lines += [f'    "{k}": "{v}",' for k, v in digests.items()]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    digests = build()
    rendered = render(digests)
    check = "--check" in sys.argv

    if check:
        current = MANIFEST.read_text() if MANIFEST.is_file() else ""
        if current != rendered:
            print("✗ _manifest.py is stale — run: python scripts/gen_manifest.py")
            return 1
        print(f"✓ manifest current ({len(digests)} files)")
        return 0

    MANIFEST.write_text(rendered)
    print(f"✓ wrote {MANIFEST.relative_to(ROOT)} ({len(digests)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
