#!/usr/bin/env python3
"""Record a SHA-256 for every shipped source file, for the runtime integrity check.

Run by the build and verified by CI, so a manifest can never drift from the code it describes —
a stale one would either fail every install or, worse, pass while describing something else.

`_manifest.py` itself is excluded: it cannot contain its own digest.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "src" / "ranbval_sdk"
MANIFEST = PKG / "_internal" / "_manifest.py"

sys.path.insert(0, str(ROOT / "src"))
from ranbval_sdk._internal.integrity import file_digest  # noqa: E402


def build() -> dict[str, str]:
    """Digests keyed by POSIX-style relative path.

    `str(Path.relative_to(...))` yields the platform separator, so a manifest generated on Linux
    and one regenerated on Windows never matched, and `--check` was permanently stale there. The
    Windows CI jobs caught it. `as_posix()` makes the file mean the same thing wherever it is
    produced, which it has to: the manifest ships inside the wheel and is verified on whatever
    machine installs it.
    """
    digests = {}
    for path in PKG.rglob("*.py"):
        if path == MANIFEST:
            continue
        digests[path.relative_to(PKG).as_posix()] = file_digest(path)
    return dict(sorted(digests.items()))


def render(digests: dict[str, str]) -> str:
    lines = [
        '"""Generated by scripts/gen_manifest.py — do not edit.',
        "",
        "SHA-256 of every shipped source file, compared at the first decrypt by",
        "``ranbval_sdk._internal.integrity``. Regenerated by the build; CI fails if it is stale.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "FILE_DIGESTS: dict[str, str] = {",
    ]
    lines += [f'    "{k}": "{v}",' for k, v in digests.items()]
    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    digests = build()
    rendered = render(digests)
    check = "--check" in sys.argv

    if check:
        # Compare the digests, not the rendered text. Comparing text made the check sensitive to
        # how the file happened to be written — newline translation, trailing whitespace, the
        # ordering of an unrelated edit — none of which say anything about whether the manifest
        # describes the current code. On Windows that produced a permanent "stale" with no way to
        # tell from the message what actually differed.
        recorded = {}
        if MANIFEST.is_file():
            namespace = {}
            exec(compile(MANIFEST.read_text(), str(MANIFEST), "exec"), namespace)  # nosec B102
            recorded = namespace.get("FILE_DIGESTS", {})

        if recorded == digests:
            print(f"OK: manifest current ({len(digests)} files)")
            return 0

        missing = sorted(set(digests) - set(recorded))
        extra = sorted(set(recorded) - set(digests))
        changed = sorted(k for k in set(digests) & set(recorded) if digests[k] != recorded[k])
        print("FAIL: _manifest.py is stale - run: python scripts/gen_manifest.py")
        if missing:
            print(f"  not recorded: {', '.join(missing[:5])}")
        if extra:
            print(f"  recorded but gone: {', '.join(extra[:5])}")
        if changed:
            print(f"  contents differ: {', '.join(changed[:5])}")
        return 1

    MANIFEST.write_text(rendered)
    print(f"OK: wrote {MANIFEST.relative_to(ROOT)} ({len(digests)} files)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
